name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[routes]]
pattern = "xiaosheng.kdns.fr"
custom_domain = true

[[d1_databases]]
binding = "db"
database_name = "cloud-mail"
database_id = "e814d982-ad0c-4e19-9103-8746feb4be83"

[[kv_namespaces]]
binding = "kv"
id = "3dde191f528a400d9f120e7604aca75a"

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = ""		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

#[vars]
#orm_log = false
#domain = []				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
#admin = ""				#管理员的邮箱	示例: admin@example.com
#jwt_secret = ""			#jwt令牌的密钥,随便填一串字符串

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
